### ISSUE TITLE
When loading the graph, the following node types were not found: IPAdapterApply

### ISSUE THREAD

**Issue by sulaymanyf** [ComfyWorkflows/ComfyUI-Launcher#30]
Hi, I get an error when I try to deploy, I tried to reinstall ComfyUI_IPAdapter_plus but the error is still there, please help me.

====-----log==================
Total VRAM 7841 MB, total RAM 7841 MB
Set vram state to: DISABLED
Device: cpu
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
****** User settings have been changed to be stored on the server instead of browser storage. ******
****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******
### ComfyUI Revision: 2096 [6c6a3925] | Released on '2024-04-02'
Traceback (most recent call last):
  File "/app/server/projects/simple-clothes-swap/comfyui/nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/server/projects/simple-clothes-swap/comfyui/custom_nodes/Fooocus_Nodes/__init__.py", line 23, in <module>
    imported_module = importlib.import_module(
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/server/projects/simple-clothes-swap/comfyui/custom_nodes/Fooocus_Nodes/py/fooocusNodes.py", line 6, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "/app/server/projects/simple-clothes-swap/comfyui/custom_nodes/Fooocus_Nodes/py/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/app/server/projects/simple-clothes-swap/comfyui/custom_nodes/Fooocus_Nodes/py/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/app/server/projects/simple-clothes-swap/comfyui/custom_nodes/Fooocus_Nodes/py/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/app/server/projects/simple-clothes-swap/comfyui/custom_nodes/Fooocus_Nodes/py/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/app/server/projects/simple-clothes-swap/comfyui/custom_nodes/Fooocus_Nodes/py/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/app/server/projects/simple-clothes-swap/comfyui/custom_nodes/Fooocus_Nodes/py/ldm_patched/modules/model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/app/server/projects/simple-clothes-swap/comfyui/custom_nodes/Fooocus_Nodes/py/ldm_patched/modules/model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/app/server/projects/simple-clothes-swap/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/app/server/projects/simple-clothes-swap/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Cannot import /app/server/projects/simple-clothes-swap/comfyui/custom_nodes/Fooocus_Nodes module for custom nodes: Torch not compiled with CUDA enabled
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

------------------ui--------

![image](https://github.com/ComfyWorkflows/ComfyUI-Launcher/assets/25156767/817f4471-630e-4289-bbb6-062b90617245)

![image](https://github.com/ComfyWorkflows/ComfyUI-Launcher/assets/25156767/1116b23e-f1b7-4e8a-821f-63f111bf8ad8)

**Comment by Whatanawfulusername** [comment]
Change the node with IPAdapter Advanced. If you dont know how to: open add node menu by clicking empty area, come to IPAdapter menu, then select IPAdapter Advanced. Link every string with new node and delete old one. IPAdapter Apply is an old version its name is IPAdapter Advanced now. Sorry for poor English skills hope it helps
