### ISSUE TITLE
Bug cloning repo on import workflow

### ISSUE THREAD

**Issue by jordibass** [ComfyWorkflows/ComfyUI-Launcher#32]
as per my log:

```
[2024-04-10 10:35:09,266: WARNING/ForkPoolWorker-1] Cloning into '/Users/jordi/Comfy_Projects/ipa-comp-style/comfyui/custom_nodes/SDXLAspectRatio.py'...
[2024-04-10 10:35:09,515: WARNING/ForkPoolWorker-1] remote: 404: Not Found
[2024-04-10 10:35:09,517: WARNING/ForkPoolWorker-1] fatal: repository 'https://raw.githubusercontent.com/throttlekitty/SDXLCustomAspectRatio/main/SDXLAspectRatio.py/' not found
[2024-04-10 10:35:09,933: DEBUG/MainProcess] Timer wake-up! Next ETA 1.0 secs.
[2024-04-10 10:35:10,934: DEBUG/MainProcess] Timer wake-up! Next ETA 0.9986971669999889 secs.
127.0.0.1 - - [10/Apr/2024 10:35:11] "GET /api/projects HTTP/1.1" 200 -
[2024-04-10 10:35:11,938: DEBUG/MainProcess] Timer wake-up! Next ETA 1.0 secs.
[2024-04-10 10:35:12,943: DEBUG/MainProcess] Timer wake-up! Next ETA 0.9948857089999876 secs.
[2024-04-10 10:35:13,940: DEBUG/MainProcess] Timer wake-up! Next ETA 1.0 secs.
[2024-04-10 10:35:14,945: DEBUG/MainProcess] Timer wake-up! Next ETA 0.9948670000000277 secs.
[2024-04-10 10:35:15,945: DEBUG/MainProcess] Timer wake-up! Next ETA 1.0 secs.
[2024-04-10 10:35:16,950: DEBUG/MainProcess] Timer wake-up! Next ETA 0.9948556250000138 secs.
[2024-04-10 10:35:17,946: DEBUG/MainProcess] Timer wake-up! Next ETA 1.0 secs.
[2024-04-10 10:35:18,948: DEBUG/MainProcess] Timer wake-up! Next ETA 0.9982914169999901 secs.
[2024-04-10 10:35:19,952: DEBUG/MainProcess] Timer wake-up! Next ETA 1.0 secs.
[2024-04-10 10:35:20,070: ERROR/ForkPoolWorker-1] Task tasks.create_comfyui_project[56a40d8f-4bab-4973-b1fb-4e03c2304400] raised unexpected: AssertionError()
Traceback (most recent call last):
  File "/Users/jordi/comfyui-launcher/venv/lib/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/jordi/comfyui-launcher/server/server.py", line 36, in __call__
    return self.run(*args, **kwargs)
  File "/Users/jordi/comfyui-launcher/server/tasks.py", line 89, in create_comfyui_project
    setup_custom_nodes_from_snapshot(project_folder_path, launcher_json)
  File "/Users/jordi/comfyui-launcher/server/utils.py", line 220, in setup_custom_nodes_from_snapshot
    run_command(["git", "clone", custom_node_repo_url, custom_node_path, "--recursive"])
  File "/Users/jordi/comfyui-launcher/server/utils.py", line 112, in run_command
    assert process.wait() == 0
AssertionError
[2024-04-10 10:35:20,954: DEBUG/MainProcess] Timer wake-up! Next ETA 0.9975047500000187 secs.
127.0.0.1 - - [10/Apr/2024 10:35:21] "GET /api/projects HTTP/1.1" 200 -
```

the main problem it tries to clone `'https://raw.githubusercontent.com/throttlekitty/SDXLCustomAspectRatio/main/SDXLAspectRatio.py/'` with the `/` at the end causing an exception.

the workflow I try to import
[IPA Comp+Style.json](https://github.com/ComfyWorkflows/ComfyUI-Launcher/files/14930092/IPA.Comp%2BStyle.json)

**Comment by HASAN3DG** [comment]
same +1

https://drive.google.com/file/d/1hth5KX9V6Le7jl3s4_bGNu8giFd3Uzyn/view?usp=sharing

**Comment by theabess** [comment]
I am also facing this issue

**Comment by altarofwisdom-perso** [comment]
Got this error as well, runnning on M1 Sonoma, importing anything fails...
[2024-07-28 22:00:55,810: ERROR/ForkPoolWorker-2] Task tasks.create_comfyui_project[9a85870c-6712-4a87-b62e-316e22fff9cf] raised unexpected: AssertionError()
Traceback (most recent call last):
  File "/Users/yoto/Projects/comfyui-launcher/venv/lib/python3.12/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/yoto/Projects/comfyui-launcher/server/server.py", line 36, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yoto/Projects/comfyui-launcher/server/tasks.py", line 89, in create_comfyui_project
    setup_custom_nodes_from_snapshot(project_folder_path, launcher_json)
  File "/Users/yoto/Projects/comfyui-launcher/server/utils.py", line 228, in setup_custom_nodes_from_snapshot
    run_command_in_project_venv(
  File "/Users/yoto/Projects/comfyui-launcher/server/utils.py", line 146, in run_command_in_project_venv
    run_command(command)
  File "/Users/yoto/Projects/comfyui-launcher/server/utils.py", line 112, in run_command
    assert process.wait() == 0
           ^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by nadalalyafaie** [comment]
I am also experiencing this same issue
