### ISSUE TITLE
Comfyui-Launcher automaticly installs newer torch whitch bricks comfyui i also get errors in comfyui- launcher and it keeps saying installing comfyui

### ISSUE THREAD

**Issue by ItsmeTibos** [ComfyWorkflows/ComfyUI-Launcher#35]
Creating virtual environment for ComfyUI Launcher...

Elementa Python ni mogo

Installing required packages...

bash: venv/bin/activate: No such file or directory
Requirement already satisfied: amqp==5.2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (5.2.0)
Requirement already satisfied: billiard==4.2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (4.2.0)
Requirement already satisfied: blinker==1.7.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (1.7.0)
Requirement already satisfied: celery==5.3.6 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 4)) (5.3.6)
Requirement already satisfied: certifi==2024.2.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (2024.2.2)
Requirement already satisfied: cfgv==3.4.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 6)) (3.4.0)
Requirement already satisfied: charset-normalizer==3.3.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 7)) (3.3.2)
Requirement already satisfied: click==8.1.7 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 8)) (8.1.7)
Requirement already satisfied: click-didyoumean==0.3.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 9)) (0.3.0)
Requirement already satisfied: click-plugins==1.1.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 10)) (1.1.1)
Requirement already satisfied: click-repl==0.3.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 11)) (0.3.0)
Requirement already satisfied: distlib==0.3.8 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 12)) (0.3.8)
Requirement already satisfied: filelock==3.13.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 13)) (3.13.1)
Requirement already satisfied: Flask==3.0.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 14)) (3.0.2)
Requirement already satisfied: fsspec==2024.2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 15)) (2024.2.0)
Requirement already satisfied: identify==2.5.35 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 16)) (2.5.35)
Requirement already satisfied: idna==3.6 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 17)) (3.6)
Requirement already satisfied: itsdangerous==2.1.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 18)) (2.1.2)
Requirement already satisfied: Jinja2==3.1.3 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 19)) (3.1.3)
Requirement already satisfied: kombu==5.3.5 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 20)) (5.3.5)
Requirement already satisfied: MarkupSafe==2.1.5 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 21)) (2.1.5)
Requirement already satisfied: mpmath==1.3.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 22)) (1.3.0)
Requirement already satisfied: networkx==3.2.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 23)) (3.2.1)
Requirement already satisfied: nodeenv==1.8.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 24)) (1.8.0)
Requirement already satisfied: numpy==1.26.4 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 25)) (1.26.4)
Requirement already satisfied: packaging==23.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 26)) (23.2)
Requirement already satisfied: platformdirs==4.2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 27)) (4.2.0)
Requirement already satisfied: pre-commit==3.6.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 28)) (3.6.2)
Requirement already satisfied: prompt-toolkit==3.0.43 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 29)) (3.0.43)
Requirement already satisfied: psutil==5.9.8 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 30)) (5.9.8)
Requirement already satisfied: python-dateutil==2.9.0.post0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 31)) (2.9.0.post0)
Requirement already satisfied: PyYAML==6.0.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 32)) (6.0.1)
Requirement already satisfied: requests==2.31.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 33)) (2.31.0)
Requirement already satisfied: show-in-file-manager==1.1.4 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 34)) (1.1.4)
Requirement already satisfied: six==1.16.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 35)) (1.16.0)
Requirement already satisfied: sympy==1.12 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 36)) (1.12)
Requirement already satisfied: torch==2.2.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 37)) (2.2.1)
Requirement already satisfied: tqdm==4.66.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 38)) (4.66.2)
Requirement already satisfied: typing_extensions==4.10.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 39)) (4.10.0)
Requirement already satisfied: tzdata==2024.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 40)) (2024.1)
Requirement already satisfied: urllib3==2.2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 41)) (2.2.0)
Requirement already satisfied: vine==5.1.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 42)) (5.1.0)
Requirement already satisfied: virtualenv==20.25.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 43)) (20.25.1)
Requirement already satisfied: wcwidth==0.2.13 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 44)) (0.2.13)
Requirement already satisfied: Werkzeug==3.0.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 45)) (3.0.1)
Requirement already satisfied: colorama in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from click==8.1.7->-r requirements.txt (line 8)) (0.4.6)
Requirement already satisfied: setuptools in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from nodeenv==1.8.0->-r requirements.txt (line 24)) (63.2.0)
Requirement already satisfied: pywin32>=301 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from show-in-file-manager==1.1.4->-r requirements.txt (line 34)) (306)

ComfyUI Launcher is starting...

Celery worker started with PID: 807
Starting ComfyUI Launcher...
Open http://localhost:4000 in your browser.
 * Serving Flask app 'server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:4000
 * Running on http://192.168.44.186:4000
Press CTRL+C to quit
[2024-04-19 15:34:00,594: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2024-04-19 15:34:00,596: DEBUG/MainProcess] | Worker: Building graph...
[2024-04-19 15:34:00,596: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, Beat, StateDB, Consumer}
[2024-04-19 15:34:00,604: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2024-04-19 15:34:00,604: DEBUG/MainProcess] | Consumer: Building graph...
[2024-04-19 15:34:00,624: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Agent, Events, Heart, Mingle, Tasks, Control, Gossip, event loop}
[2024-04-19 15:34:00,624: WARNING/MainProcess] No hostname was supplied. Reverting to default 'localhost'

 -------------- celery@ASUS22 v5.3.6 (emerald-rush)
--- ***** -----
-- ******* ---- Windows-10-10.0.22631-SP0 2024-04-19 15:34:00
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         server:0x28806279540
- ** ---------- .> transport:   filesystem://localhost//
- ** ---------- .> results:     file://.celery%5Cresults/
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery

[tasks]
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . tasks.create_comfyui_project

[2024-04-19 15:34:00,662: DEBUG/MainProcess] | Worker: Starting Pool
[2024-04-19 15:34:00,674: CRITICAL/MainProcess] Unrecoverable error: AttributeError("Can't pickle local object 'celery_init_app.<locals>.FlaskTask'")
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\celery\worker\worker.py", line 202, in start
    self.blueprint.start(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\celery\bootsteps.py", line 116, in start
    step.start(parent)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\celery\bootsteps.py", line 365, in start
    return self.obj.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\celery\concurrency\base.py", line 130, in start
    self.on_start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\celery\concurrency\prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\billiard\pool.py", line 1045, in __init__
    self._create_worker_process(i)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\billiard\pool.py", line 1157, in _create_worker_process
    w.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\billiard\process.py", line 120, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\billiard\context.py", line 381, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\billiard\popen_spawn_win32.py", line 81, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\billiard\reduction.py", line 98, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'celery_init_app.<locals>.FlaskTask'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\billiard\spawn.py", line 164, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\billiard\spawn.py", line 206, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input

**Comment by rokonezoko55555555** [comment]
are you a hugging space pro user ? paid user
